In [6]:
class demo:
    def test(self):
        print("test() for the class and method")
        return
obj=demo()
obj.test()

test() for the class and method


In [7]:
def test():
    print('test() for function')
    return
test()

test() for function


In [18]:
class demo1:
    def fact(self,n):
        #return the factorial
        fact=1
        while(n!=0):
            fact=fact*n
            n=n-1
        return fact
    
p1=demo1()
p1.fact(5)#120

120

In [3]:
class demo2:
    def __init__(self,p1,p2):
        self.p1=p1
        self.p2=p2
    def add(self,p1,p2):
        return p1+p2
c1=demo2(10,20)
print(c1.add(100,200))

300


In [11]:
class person():
    #constructor
    def __init__(self,name):
        self.name=name
    def getname(self):
        return self.name
    def isemployee(self):
        return False
#derived class
class employee(person):
    def isemployee(self):
        return True
emp=person("anil")
print(emp.getname(),emp.isemployee())
emp1=employee("akhil")
print(emp1.getname(),emp1.isemployee())

anil False
akhil True


In [13]:
import numpy as np
lst=[1,2,3,4]
array=np.array(lst)
print(array)

[1 2 3 4]


In [14]:
lst=[1,2,3,4]
array=np.array(lst)
print(array.shape)
print(array.dtype)

(4,)
int32


In [15]:
lst=[1.0,2.5,3.6,9.5]
array=np.array(lst)
print(array.shape)
print(array.dtype)

(4,)
float64


In [16]:
lst=[1.0,2.5,3.6,9.5]
array=np.array(lst)
print(array.shape)
print(array.dtype)

(2, 3)
(3, 2)


In [17]:
a1=np.array([(1,2,3),(4,5,6)])
print(a1)
a1.reshape(3,2)

[[1 2 3]
 [4 5 6]]


array([[1, 2],
       [3, 4],
       [5, 6]])

In [18]:
a1=np.array([1,2,3])
a2=np.array([4,5,6])
print(np.hstack((a1,a2)))

[1 2 3 4 5 6]


In [21]:
a1=np.array([1,2,3])
a2=np.array([4,5,6])
print(np.vstack((a1,a2)))

[[1 2 3]
 [4 5 6]]


In [22]:
a1=np.random.normal(5,0.5,10)
print(a1)

[4.28785832 4.75263998 4.50512442 4.95859727 4.40510884 5.58163016
 5.52704532 4.50121412 5.32640137 4.66599825]


In [23]:
np.zeros((2,2))

array([[0., 0.],
       [0., 0.]])

In [24]:
np.ones((2,2),dtype=np.int64)

array([[1, 1],
       [1, 1]], dtype=int64)

In [38]:
np.ones((4,3),dtype=np.int64)

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]], dtype=int64)

In [3]:
import numpy as np
A=np.matrix(np.ones((4,4),dtype=np.int64))
print(A)

[[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]]


In [6]:
import numpy as np
A=np.matrix(np.ones((4,4),dtype=np.int64))
print(A)

[[1 1 1 1]
 [1 1 1 1]
 [5 5 5 5]
 [1 1 1 1]]


In [8]:
import numpy as np
np.arange(1,10)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [9]:
np.arange(1,100,9)

array([ 1, 10, 19, 28, 37, 46, 55, 64, 73, 82, 91])

In [10]:
np.arange(2,20,2)
np.arange(1,25,2)

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19, 21, 23])

In [11]:
np.arange(2,20,2)
np.arange(1,25,2)

second row: [4 5 6]


In [12]:
a1=np.array([(1,2,3),(4,5,6)])
print("slising colum :",a1[:,1])

slising colum : [2 5]


In [13]:
a1=np.array([(1,2,3),(4,5,6)])
print("slising colum :",a1[1,:2])

slising colum : [4 5]


In [14]:
a1=np.array([(1,2,3),(4,5,6)])
print("row and coloum:",a1[1,:2])

row and coloum: [4 5]


In [15]:
a1=np.random.normal(5,1,10)
print(a1)
print("min values =",np.min(a1))
print("max values =",np.max(a1))
print("mean value=",np.mean(a1))
print("median value =",np.median)

[5.07761544 4.55959086 2.86393677 3.91784368 4.37332984 4.34061942
 4.92516309 4.66180808 4.15521144 3.72557602]
min values = 2.8639367675677203
max values = 5.077615441256833
mean value= 4.2600694627064275
median value = 4.356974628710072


In [16]:
c1=np.array([1,2])
c2=np.array([4,5])
np.dot(c1,c2)

14

In [17]:
c1=np.array([(1,2),(3,4)])
c2=np.array([(3,4),(1,2)])
np.dot(c1,c2)

array([[ 5,  8],
       [13, 20]])

In [18]:
b1=np.array([(1,5),(6,9)])
b2=np.array([(1,3),(1,6)])
np.matmul(b1,b2)

array([[ 6, 33],
       [15, 72]])

In [3]:
import pandas as pd
dict={"name":["saketh","kushal","uma"],"emailid":["vsakethrao19@gmail.com","kushalreddy@gmail.com","uma2000@gmail.com"],
      "mobilenumber":["9553706121","8117456325","9848561236"],"address":["hyd","hyd","hyd"]}
b=pd.DataFrame(dict)
print(b)

     name                 emailid mobilenumber address
0  saketh  vsakethrao19@gmail.com   9553706121     hyd
1  kushal   kushalreddy@gmail.com   8117456325     hyd
2     uma       uma2000@gmail.com   9848561236     hyd


In [4]:
b.index=["01","02","03"]
print(b)

      name                 emailid mobilenumber address
01  saketh  vsakethrao19@gmail.com   9553706121     hyd
02  kushal   kushalreddy@gmail.com   8117456325     hyd
03     uma       uma2000@gmail.com   9848561236     hyd
